name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Decode and Setup SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > private_key.pem
        chmod 600 private_key.pem
        eval $(ssh-agent -s)
        ssh-add private_key.pem

    - name: Deploy to EC2 via SCP and SSH
      run: |
        scp -o StrictHostKeyChecking=no -r ./index.html ubuntu@${{ secrets.EC2_HOST }}:/tmp/
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          sudo mv /tmp/index.html /var/www/html/index.html
          sudo systemctl restart nginx
        EOF
